export const TEST_SUCCES = "TEST_SUCCES";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";

export const CREATE_OKTA_USER_SUCCESS = "CREATE_OKTA_USER_SUCCESS";
export const CREATE_OKTA_USER_FAILURE = "CREATE_OKTA_USER_FAILURE";

export const SEND_ACTIVATION_MAIL_SUCCESS = "SEND_ACTIVATION_MAIL_SUCCESS";
